var dateIdeas = { 
  '0': 
   [ { name: 'Cuddling on the Couch',
       description: 'Light a candle on the table and dive under the blanket together. Likelihood of falling asleep mid-cuddle is high.' } ],
  '1': 
   [ { name: 'Indoor stargazing',
       description: 'Lay on couch (or hammock!) indoors. Pull out Google Sky. Tell stories of where you imagine the two of us seeing these stars in person. Avoid booking more than 2 trips tonight.' },
     { name: 'Write notes to our grandmothers',
       description: 'No pithy description here. I just want to talk to my grandma more. ' },
     { name: 'Read to each other',
       description: 'Don\'t knock it \'til you try it. ' } ],
  '2': 
   [ { name: 'Hammock',
       description: 'Lay in hammock. Cuddle. Point out constellations inaccurately. Hope that the two Newfoundlands this hammock is strapped to don\'t dive into the water with us.' },
     { name: 'Eat way too much popcorn',
       description: 'Enter the movies. Buy tub of endless popcorn. Watch movie. Surreptitiously (you know, with the high-knee walking, hunched back, and cackling laughter) sneack into the next film. Refill popcorn. Repeat. Make sure to go to a new popcorn counter each time. Wear boring clothes. Pass out in a butter-drenched haze of explosions and implausibly perfect relationships. Savor your own imperfect match even more.' },
     { name: 'Creative Cuddles',
       description: 'Spooning\'s a great position to cuddle in. But so is the mellow dragon, and the fierce chipmunk. Not familiar with those cuddling positions? Neither am I, but let\'s make them up! Take inspiration from yoga and dance and the kama sutra- people can do way more creative things with their bodies than most of us take advantage of while cuddling. ' },
     { name: 'Hometown tours:',
       description: 'I think it\'s cool to see where you grew up. And it\'s cathartic to show you where I got stuffed into a dumpster after school every day. Err, I mean, why I learned to run really fast and the trails we chose. Thanks to the magic of Google Earth and Google Street View, we can give each other a hometown tour while never having to leave our cuddly couch. ' },
     { name: 'Look up family trees together online ',
       description: 'I\'m not at all sure if this is possible. If not, just tell tales of your ancestors. Believability is not required in this case :)' },
     { name: 'Write a poem together',
       description: 'Or, if we\'re feeling more adventurous, we can freestyle rap together. Each person gets no more than 10 seconds per line, or 30 seconds per stanza. Speed chess meets slam poetry meets date night. There\'s a good chance this will not end well. ' },
     { name: 'I\'m touching you',
       description: 'Spend an hour where the only ruls is that we pick two body parts, and those two body parts must be touching the entire hour. Toe to nose, or fingers to delicious scalp massage are both acceptable, depending on mood. ' },
     { name: 'Spend an hour blindfolded',
       description: 'I think it\'d be fun to work on a couple variations of this: both people blindfolded at once, then one person seeing and one person blindfolded. I have no hypothesis for what the results of this experiment will be. Which makes me highly intrigued to try it. ' },
     { name: 'I can\'t hear you',
       description: 'Spend an hour doing something together with ear plugs in, and not talking to each other. Laughing is (oddly) discouraged. We can only communicate with eyes and bodies and foot signals and ravens. This is good training for playing cards together and sneakily telling each other about our hands to destroy the other teams. ' } ],
  '3': 
   [ { name: 'Bonfire at the beach',
       description: 'Fire. Gentle drumbeat of waves. "The next time the sand shares our weight as the sunset glazes the horizon, I\'d love to wrap your fingers through mine, and see what happens."' },
     { name: 'Make up your own constellations',
       description: 'The ancients aren\'t the only ones capable of seeing fantastic things in the sky. I\'m pretty sure that\'s my younger brother up there wrestling an ice cream cone in a ball pit.' },
     { name: 'Telling stories from each others\' closets',
       description: 'Go through the other person\'s closet. Make an outfit from their clothes, and then tell a story of the kinds of events you imagine they\'ve worn this outfit to in the past. Claims of superhero-dom do not need to be refuted. ' },
     { name: 'Plot a road trip on google maps',
       description: 'Travel the country without leaving the cuddly blanket the two of us share. Each of us gets to plot a road trip. The parameters are up to you- whether this is a weekend road trip, a 3 week blitz, or a 3-year extravaganza!' },
     { name: 'Create a pot of melted chocolate',
       description: 'Dip things in it. ' },
     { name: 'Dumpling making night!',
       description: 'Make dumping mix. Buy dumpling shells. Make contemporary art putting the two together in creative ways. Eat any of our creations that aren\'t museum-worthy. ' },
     { name: 'Smoothie making night ',
       description: '\'Smoothie pops\'. Why pops? Toss the smoothies into the freezer in relatively small containers, and then enjoy them throughout the whole next week, or during that day\'s adventure! Try all combinations of rotting fruit and kale juice you can think of until you find something even a hipster wouldn\'t sip. ' },
     { name: 'Marshmallow castles. ',
       description: 'Build castles. With marshmallows. ' },
     { name: 'Guacamole  of everything ',
       description: 'Guacamole is scientifically proven to be goddess Athena\'s favorite food on Thursdays. Let\'s see if we can make it her favorite food every day of the week by changing it up. Buy ingredients. Add to a small scoop of guacamole. See if chocolate or ginger or bacon or salmon or beef jerky or ice cream make guacamole better. Appease Athena. ' },
     { name: 'Giving pizzas',
       description: '14th century Sicilian monks found the secret to life when they discovered pizza (definitely an accurate creation story for pizza). This makes it really easy to give each other great gifts: just make each other pizza! We\'ll have a pizza making night with a twist: each of us is not allowed to eat a single bite of the pizza you make- it\'s exclusively going to the other person. Whether you use this as an excuse to make that thing the other person loves but you abhor (oyster pizza with a lamb ragu), or to go a bit more adventurous in what they\'re eating for the night, is up to you!' },
     { name: 'Mix your own cocktails',
       description: 'Ever felt like all those fancy cocktails could really just be described as booze mixed with some sassy sassafrass? Well pick out your own ingredients and see if you can one-up those showy bartenders in either creativity, tastiness, showmanship, or cool hairdo. Leave with a renewed appreciation for bartenders, and a whole lot less sassafrass in the herb cabinet. ' } ],
  '4': 
   [ { name: 'Guacamole Tour',
       description: 'Have one person pick up a smorgasboard of their favorite guacamoles. Bonus combinations come from picking up an equally large array of favorite things to dip in guacamole (be careful- carrots are contentious, chocolate-dipped bacon will get you creativity points, and your date\'s toe will quickly establish whether they share your foot fetish or not).' },
     { name: 'Remote Museum Tour',
       description: 'Museums are a way to travel to fantastical far off lands, visit places that vanished long ago, and explore incomprehensible ways of life. But, in order to visit them, you generally have to travel to fantastical far off lands. Which builds in some odd circular logic. Let\'s avoid that infinite loop by teleporting our eyes to a museum, while we cuddle on the couch together! Google Maps has our back.' },
     { name: 'Climb El Cap',
       description: 'Ok, admittedly, most people don\'t consider hauling around bags of your own poo a particularly romantic activity. And most of us would never be able to keep up with Alex Honnold, Lynn Hill, and Tommy Caldwell. Happily, due to the magic of Google Maps, you can enjoy all this from the comfort of your own armchair! https://www.google.com/maps/about/behind-the-scenes/streetview/treks/yosemite/' },
     { name: 'Plan a vacation on a budget of 10 days and $1500',
       description: 'Don\'t ask where the 10 days and $1500 came from. Maybe I finally figured out alchemy. Or time travel? Either way, you needn\'t bother with such trivial details- time to start planning what you would do within such constraints!' },
     { name: 'Massages',
       description: 'Simple: push as many of your body parts (fingers, thumbs, elbows, knees, feet, head, glutes, tail, etc.) into as many of their body parts as possible. I\'ll be yelping in pain the whole time because my body\'s tight. This is romantic, right?!' },
     { name: 'Viewpoint at the top of the de Young',
       description: 'It\'s an incredible, glass-walled 360 panorama of the whole city, from a perspective that few other vantage points offer. It\'s a peaceful room in a super-modern style that manages to feel very comfortable and welcoming. Plus we get to talk about architecture, earthquakes, statues, dissonance, weathering, and the effects of crowds, while enjoying this totally free viewpoint!' },
     { name: 'Picnic at the alice marble tennis courts',
       description: 'Theoretically, they\'re tennis courts. That get reliably too windy to play tennis on. That are at the top of one of the most scenic hills in SF, literally surrounded by Lombard Street, the cable cars, views to Alcatraz and the Golden Gate Bridge, and a park. Realistically, they\'re an amazingly reliable and peaceful picnic area. ' },
     { name: 'Ride the cable cars',
       description: 'Appreciate the brilliant engineering, allow yourself to time travel back to the earliest days of SF, put yourself in the mindset of a tourist, or just enjoy the ride. They run late into the night, well past when all the tourists clear out :)' },
     { name: 'Magazine store',
       description: 'It\'s crazy to find all the niches that exist in this world. And really fun to find the ones that you\'re into that I didn\'t know about yet. Toss in the chance of finding some good reading material, and we\'re all set!' },
     { name: 'Cook half-planned dinner',
       description: 'Each of us picks out half the ingredients. Neither of us tells the other what we picked up until we arrive in the kitchen. Both of us figure out how to make something from this. ' },
     { name: 'Top chef challenge',
       description: 'Pick an ingredient, and make a meal around it! ' },
     { name: 'Rent a car and go stargazing somewhere just outside of the city',
       description: 'By that time of the night there\'s no traffic around. It\'s surprising how peaceful it is just 5 miles out of the city. This would be particularly great for one of the many meteor showers. ' },
     { name: 'Chocolate crawl',
       description: 'My momma loves chocolate. I mediocre chocolate. I like buying chocolate for my momma. Let\'s go on a tour to find the best chocolate around!' },
     { name: 'Learn new massages',
       description: 'The best way to learn something is by doing. Trust me, I\'m a professional educator. For our own sake, we should practice new massage techniques on each other. ' },
     { name: 'Massaging each other at the same time:',
       description: 'Every discipline has the beginner technique that everyone thinks they can do. Bouldering has alligator holds, for example. But most disciplines look dramatically different once you start to get good at them. Bouldering has whiskey drinking, for example. Let\'s practice advanced massaging by massaging each other at the same time. What does this entail? I have no idea, I\'m still stuck pondering why people are trying to climb on alligators. ' },
     { name: 'Dim sum ',
       description: 'I still remember eating my first chicken foot from nearly a decade ago. Let\'s see if we can go make any other lifelong memories by ordering anything on the menu we don\'t recall eating before. For the rest of the afternoon, check out the date ideas under energyLevel 1: food coma. ' },
     { name: 'Set up a tent',
       description: 'Inside we can have board games and a bottle of wine and headlamps and adventure stories and hear bear noises and be protected from 80 mph gale-force political bluster. All from the comfort of a quiet park, or one of our living rooms. ' } ],
  '5': 
   [ { name: 'Artisanal Popcorn Showdown',
       description: 'Get giant box of raw popcorn kernels. No, not the kind that come pre-deliciousized for you by Orville Reddenbacher (sp?), but the kind you have to pop on the stove yourself. Bring flavors that would be at home in a crazy donut shop, a farmers market, or the latest hipster haunt. Compare batches, tournament style. Make up crazy names for each flavor combination you conjure up. Picture world domination and population-wide health improvements through running a chain of artisanal popcorn shops.' },
     { name: 'Jungle Crawl',
       description: 'Crawling around dirty bars sounds much less fun than crawling around the jungle. Let\'s go exploring the plant and flower stores around, and imagine ourselves in the exotic locales where these plants originally grew. ' },
     { name: 'Walk along the waterfront',
       description: 'Not much to this one: I love being by the water. I love holding your hand. I love walking in places that stimulate introspection, where the setting itself encourages emotional depth and vulnerability, where the consistency of the waves washing in allows us to savor the inconsistency of the journeys we took to get here, where... ok, maybe there is a bit more to this one. ' },
     { name: 'Wave organ',
       description: 'Some tribe of giants tried to recreate a Greek temple in the middle of the Bay, it got swallowed by the sea, Atlantis style, but the top of it has re-emerged in recent years and we built a land bridge to reach it. Oh, and there\'s an organ there. Played by the waves themselves. At least one part of this is half-true. What\'s undeniably true is that this is my favorite places IN the Bay. ' },
     { name: 'Sit on a bench and give a compliment to everyone who passes',
       description: 'This is far less creepy to do as a couple than to do alone. Unrelatedly, let\'s give a wide berth to the intersection of Duboce and Sanchez. It\'s a great excuse to practice finding things to appreciate about people. ' },
     { name: 'Any of the climbing movie events',
       description: 'Advertising is super effective. No, I don\'t know this from working on the data side of the ad industry for years measuring the effectiveness of ads. I know this from my friend Pete. Climbing movies are basically the best advertising that I\'ve found yet for going climbing. Let\'s top up our stoke!' },
     { name: 'Super divey whiskey bar',
       description: 'Super pretentious whiskey selection. Graffiti on the walls. Bartenders that can respond to requests along the lines of \'I like this, but could you find something with a bit more castle dungeon, and a hint of hippogriff feather?\'. Sticky seats. It\'s a wonderful study in contrasts. ' },
     { name: 'Ride the elevators in tall hotels',
       description: 'I never thought I\'d hear myself saying this, but let\'s hope the glass ceiling doesn\'t break...' },
     { name: 'Explore all the community gardens',
       description: 'Heartfelt moment here. These are some beautiful spaces taken care of by dedicated neighbors, that are open for all of us to appreciate, and typically well off the beaten path. It\'s inspiring to see the care people devote to these gardens. Let\'s go savor these strikingly peaceful places. ' },
     { name: 'Create new fusion dishes ',
       description: 'Middle-eastern burrito, or hamburger pho, anyone?' },
     { name: 'Art walks',
       description: 'They seem to happen every week in the Bay Area. Galleries stay open late, people wander through, pondering art as an excuse to drink way more heavily than they otherwise would on a weeknight. Whether you\'re into art or drinking, this is an event for you!' },
     { name: 'Dim sum picnic',
       description: 'There\'s something about dim sum that shouts beach and picnic. Let\'s put an end to the shouting. ' },
     { name: 'Sushi',
       description: 'Order everything that comes around that you don\'t remember eating before. For me this is everything because I have a short sushi memory. Mmmmmmmm :)' } ],
  '6': 
   [ { name: 'Board Games at a Bar',
       description: 'Many bars around have board games! What better way to test out your date\'s capability of world domination? Popular places include: Victory Pointe Cafe (Berkeley), Sycamore, The Wreck Room, Soda Popinski\'s, and anything else on this list: https://www.yelp.com/search?find_desc=board+games+bar&find_loc=San+Francisco%2C+CA' },
     { name: 'Dress each other up for a night',
       description: 'You get to avoid all the decision-making of picking out your outfit for your hot date tonight- because they\'ll be picking out your outfit for you! Whether you choose to coordinate on both creating sexy/silly/creative outfits, or just go it alone and surprise them, is up to you. ' },
     { name: 'Scoot!!',
       description: 'Zip zip! Vroom vroom! I dare you to go for a ride on one of these spunky red Vespa-type things and not emerge with a silly smile on your face. No motorcycle license required. ' },
     { name: 'A single drink at a ridiculously fancy bar',
       description: 'Expensive dates feel weird. But feeling fancy can be fun! Get the best of all worlds by having a single drink at a ridiculously fancy bar, and nursing it for a long, long time while savoring some people watching, or pretending to be billionaires. ' },
     { name: 'Privately owned public spaces',
       description: 'Many of SF\'s tallest buildings have public areas in them, and oftentimes at or near the very top! It\'s the best of many worlds: we get the feeling that we\'re practicing our ninja skills while still being totally legal, a great view, and frequently, we\'ll get the whole place to ourselves. ' },
     { name: 'Thrift store $15 for each other',
       description: 'Grab $15. It\'s a shallow excuse to go play and flirt in all the many stimuli a thrift store offers. The only constraints are that we can only spend that $15 on each other, and whatever we buy the other person has to wear for the rest of the night. If I finally find that ideal cast-iron skillet, we might find that kitchenware is the new style this season...' },
     { name: 'Musee Mecanique',
       description: 'Yes, it\'s by Pier 39. Yes, it\'s on nearly every \'56 Fun Dates To Take Down the Coffee Industry By Never Going To A Gosh-Damned CoffeeShop On A Date EVER AGAIN\' list. Yes, it\'s incredibly fun. Yes, it\'s incredibly cheap. Yes, I will totally kick your butt at having my palm read. ' },
     { name: 'Walking labyrinths',
       description: 'There are several scattered throughout our city. Each one placed to allow quite a journey in their 20-foot diameter. We can meet in the middle and cuddle, make eyes at each other as we brush past on criss-crossing paths, or just each enjoy our own time and emerge from the other end as peacefully as if coming out from meditation or yoga, in a beautiful setting. ' },
     { name: 'The Ribbonerie',
       description: 'It\'s an entire store dedicated to ribbons. I smell a drug front. Let\'s go. ' },
     { name: 'Climb trees',
       description: 'Sit in trees. Talk in trees. Cuddle in trees. Make mountain lion noises at unsuspecting passers-by from trees. Try to drop leaves into coffee cups from trees. Find new neighborhoods to climb trees in. Sit in trees. Cuddle in trees...' },
     { name: 'Stationary travel',
       description: 'Stand at a vista point. Imagine ourselves somewhere totally different, like the Grand Canyone. Describe what it\'s like to be there, and transport each other with our words and imagery to a land thousands of miles (or millions of universes) away. ' },
     { name: 'Rent an airbnb for a night',
       description: 'Become a visitor in our own city, just to get a taste of someone else\'s life, and change things up a bit. ' },
     { name: 'Gallery hopping',
       description: 'Galleries are fun. Using dark magic to slip inside peoples\' minds is fun. Put the two together by putting on a different person\'s perspective for each new gallery we go to!' },
     { name: 'Flowers & Nature & Gardens',
       description: 'SF has no shortage of officially curated Nature. Conservatory of Flowers. Japanese Tea Garden. The Botanical Garden. Who needs to leave the city to find the outdoors when they\'ve put so much effort into bringing it to us. Sarcasm aside, these are much better places to lounge around than a dirty street corner. ' },
     { name: 'Nerd nites',
       description: 'I\'ve never been, but the name alone has had me intrigued for years. ' } ],
  '7': 
   [ { name: 'Escape the Room!',
       description: 'Pit your combined wits against an impending zombie horde, or time-travelling machine about to go haywire, in one of the many escape-the-room games around. If you\'re really unlucky, you might just time travel all the zombies to the past, when our ancestors were particularly susceptible because they hadn\'t seen all the movies yet and prepared for the zombie apocalypse.' },
     { name: 'Mischevious Ice Cream Promenade',
       description: 'Tour around to all your local ice cream & gelato favorites. Get a taster spoon of all the good-looking flavors. For extra weirdness points, blindfold one person. To avoid burning out too early, only sample flavors at each place- don\'t actually buy any ice cream. Tip super generously. Giggle tremendously while running out so that all other customers assume you two hooligans are surely up to no good.' },
     { name: 'Dress each other up ridiculously for a night of adventuring',
       description: 'Let\'s face it- wearing ridiculous outfits is fun. But oftentimes we lack imagination or guts to wear the best outfits lurking in our closets. So have your date pick out an attention-grabbing outfit for you! This is best done on nights when there is an adventure planned (rock climbing comes easily to mind).' },
     { name: 'Blues dancing',
       description: 'It\'s a style of movement designed around connecting with your partner, moving slowly, and just feeling some incredible music. I know just enough to lead you in a fun night of dancing after the intro class they offer before each session!' },
     { name: 'Create an algorithm that will lead you through the city randomly',
       description: 'Your choice whether the algorithm development, or following it\'s instructions, is the date part :)' },
     { name: 'Exploratorium after dark',
       description: 'Science + booze + no kids around + experiments + being on a pier right on the water = ... I never did pay enough attention in chemistry class to figure out how those elements will combine. ' },
     { name: 'Dance floor at the Top of the Mark',
       description: 'Fantastic martinis. Great views out over the city, particularly for sunset. Live band. Dance floor. No risk of being overrun by hipsters who wouldn\'t be caught dead in a place as old-timey formal as this. ' },
     { name: 'Drop into a house showing playing the role of a different couple',
       description: 'Ideally without telling each other anything about the roles that each of us picked. ' },
     { name: 'Visit ridiculous museums neither of us imagined existed',
       description: 'SF has a museum for everything, including the American Bookbinder\'s Association. Let\'s go seek out some of the more unexpected museums around and see what worlds existed we never would have imagined!' },
     { name: 'Park hopping ',
       description: 'Find all the tiny parks. Do something ridiculous in each one (take a swig of wine, leave a flower, climb a tree, do a yoga pose, talk through what a future could look like one year at a time, imagine being an archaeologist from the future back to visit this area after the Earth has been towed further out into space by giant tractor beams 4.8 billion years form now...).' },
     { name: 'Go through all the alleyways',
       description: 'SF has some cool alleyways, from the graffiti\'d tunnels of the Mission and SoMa, to the steep half-blocks that turn into steps in Nob Hill. Different adventures to be had in each neighborhood, from sanguine to spicy. And good practice for Melbourne :)' },
     { name: 'Contact improv',
       description: 'Contact improv is my kind of dance: the only rule is that at least one part of your bodies must remain touching at all times. The rest is totally made up. Where was this back in middle school?! Let\'s do some contact improv, either at the weekly wednesday jams, or just making stuff up on our own!' },
     { name: 'Morning ride/walk to sunrise on top of twin peaks ',
       description: 'Ok, I\'ll admit it now- I\'d actually just hijack this ride to Sutro Heights or Mt. Davidson. Right nearby, and much more interesting sunrise vistas. ' },
     { name: 'Lawn bowling in GGP',
       description: 'Just as every society has invented the dragon, it seems every society has invented various forms of bocce ball. Come try out this arcing and fancy version with a free intro class at the Lawn Bowling Club in GGP!' },
     { name: 'Practice fishing casting in GGP',
       description: 'I generally prefer hunting for fish in the supermarket, or with a stick of dynamite, but if you prefer the old-fashioned way, there\'s a series of ponds in the middle of the park designed exclusively to practice your casting in. I prefer to use them for riding figure 8\'s on my bike.' },
     { name: 'Hill walk',
       description: 'I love going up hills. It might be a sickness of mine. Sadly, it doesn\'t appear to be easily contagious, because the top of most hills is beautiful and empty. Let\'s grab a hammock, and use all that walking as an excuse to sit on top for a while!' } ],
  '8': 
   [ { name: 'Roadtrip Game- City Walking Edition',
       description: 'A new twist on the classic roadtrip game of looking out the window and seeing whose side has more (cows/ice cream stands/bubble gum factories). At each intersection, alternate who chooses which way to turn. After their choice, count up however many (flowers/babies screaming/used needles/couples making out surreptitiously) you pass before the next intersection.' },
     { name: 'Whale boating',
       description: 'HEAVE! Your choice whether you see this HEAVE! as a celebration of nostalgic masculinity HEAVE! during a time when peoples\' strength and daring HEAVE! determined whether they emerged from the seas or HEAVE! not, or whether this is a celebration of HEAVE! our world\'s increasing civility, a waning of HEAVE! violence, an increased appreciation of nature, and HEAVE! reclaiming old practices as new social pursuits. HEAVE! Either way, we\'ll spend some great time HEAVE! on the water and getting in a workout. HEAVE!' },
     { name: 'Sneaking into places you\'re not technically allowed...',
       description: 'Details can be found at REDACTED' },
     { name: 'Hip hop class',
       description: 'There are some incredible hip hop classes in the city. Let\'s go learn how to bust a move, while getting in a great workout and having an awesome time moving our bodies!' },
     { name: 'Gettin\' crafty with it:',
       description: 'Go to a home improvement or craft store. Buy $14 worth of supplies each. Do not coordinate. Build things. ' },
     { name: 'Tandem bike ride',
       description: 'Because nothing says romantic like being clipped into a metal pole together, hurtling through crowds and traffic at 20 mph, while one of us gets intimately familiar with the others\' hips. I\'m so excited!' },
     { name: 'All the urban hikes',
       description: 'If you want to walk, I have no shortage of scenery for us to walk through. Just say the word and we\'ll zip through fantastical lands contained within our very own city. And get in enough movement to enjoy some great food afterwards. ' },
     { name: 'Full-moon kayaking',
       description: 'I know nothing more than the name suggests. I\'m incredibly excited by this idea. ' },
     { name: 'Rental paddle boats!! ',
       description: 'Rental paddle boats are silly. Crushing the competition and destroying PRs is not. Let\'s rent a paddle boat, and once we\'re done monkeying around, race around the lake in circles, make a Strava segment from it, and collapse into victory beers at the end as exhausted as Olympic rowers. ' } ],
  '9': 
   [ { name: 'Stair Climber',
       description: 'Start in a hilly part of town, with back pathways criss-crossing their way through alleys and community gardens to the top of a hill. Climb said stairs. Then luge/walk/bike/scoot/Uber/dragon/bobsled to the next hill, and repeat!' },
     { name: 'Stand up paddle boarding',
       description: 'What better way to test our animal magnetism than to dress ourselves up as a giant seal and float slowly along the water?!' },
     { name: 'Morning bike ride up Hawk Hill',
       description: 'I\'ve poured paragraphs of words onto the golden gate as we race a sunrise to the top of this hill. To get a proper description of this ride you\'ll have to join me one of these mornings. Not sure you\'ll make it? Don\'t worry, these rides always start with drugs (coffee!) and tasty tasty snacks (donuts!). ' },
     { name: 'Archery in GGP ',
       description: 'There\'s a free archery range in GGP. Time to call up your friend the Green Hornet (did I successfully make a pop culture reference there?!) and practice drawing with pointy arrows. ' } ],
  '10': 
   [ { name: 'Morning dance party',
       description: 'Why stay up late to dance the night away only to feel awful and hungover the next day, when you can wake up early to dance the morning away and feel fantastic all day aftewards? The only drugs allowed are coffee and brightly colored pants. ' },
     { name: 'Morning ride to Muir Beach',
       description: 'This stretch of road convinced me to move out here back in high school. With an early start, we can still make it back in time for work. And you will have gotten to start your day with something most people only get to dream of. ' },
     { name: 'Go to one of the public workout areas',
       description: 'SF has decided that the best way to slim everyone down is to scatter free workout equipment throughout the city. Let\'s put it to use! We\'ll use every machine, ideally none of them in an obvious way. Sweat + creativity + hugs + food afterwards puts this date high on my yet-to-do list!' },
     { name: 'GG Park workout stations',
       description: 'There\'s a circuit of interesting exercise equipment scattered around the polo field in Golden Gate Park. Which means we get to combine exploring, nature, and creative workouts all in one! I\'ve wanted to do this circuit for years. Care to join me on it?' } ] 
};
